# Generated by Django 4.2.13 on 2024-06-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Others")],
                        max_length=1,
                    ),
                ),
                ("years_of_experience", models.PositiveSmallIntegerField()),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=100)),
                ("current_salary", models.IntegerField()),
                ("expected_salary", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Applied", "Applied"),
                            ("Shortlisted", "Shortlisted"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Applied",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
