# Generated by Django 4.2.13 on 2024-06-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usersearch", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="age",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
